### PR TITLE
Update RKE to 1.4.5

### PR DESCRIPTION
**Pull request by tsde**
Bump RKE version to 1.4.5 which brings Kubernetes v1.25

Changes includes

- Update RKE version to 1.4.5
- `go mod tidy` to ensure all deps are in sync
- Fix references to `rancher.Configuration` and `rancher.Limit` types that don't exist anymore and switch to using the `eventratelimitapi.Configuration` and `eventratelimitapi.Limit` types instead

Personal testing :

- `make test` and `make testacc` are all green
- Popping a 1.25 cluster is OK
- Updating from k8s 1.24 (based on RKE 1.4.3) to 1.25 is also OK

### CODE REVIEW

**Comment by dje4om** [comment]
Hi @a-blender, would it be possible to take a look at this PR and publish a new version of the provider to allow kubernetes 1.25 cluster deployment?

Thanks!

**Review by a-blender — CHANGES_REQUESTED** [review]
@dje4om I can do you one better. The tf rke provider is supposed to have parity with rancher, which means use the same packages that rancher uses under the hood. Rancher currently uses [rke v1.4.6-rc3](https://github.com/rancher/rancher/blob/c842598344ee552daf5cf4e8d31d6e11621e07ad/go.mod#L120) which will probably be unRC'd to v1.4.6 for the upcoming Rancher 2.7.x. Could you please update rke in the provider to [v1.4.5](https://github.com/rancher/rke/releases/tag/v1.4.5) in this PR and make sure the tests you ran before still pass? That will be helpful for our test team.

**Comment by tsde** [comment]
Hi @a-blender and thanks for your feedback
As you requested, I just update the RKE dependency to 1.4.5 and updated the description accordingly.
I also ran the same tests without any issues.

Do you have any ETA regarding RKE v1.4.6 ? Is it expected to land in a few days/weeks ?

**Comment by a-blender** [comment]
@tsde Please re-request me as a reviewer next time or I'll miss that you updated ;)

Glad I checked. Unsure about v1.4.6 cc @kinarashah

**Review by a-blender — APPROVED** [review]

**Comment by tmsdce** [comment]
Hi @a-blender @kinarashah 
Is there something more to do on my side for this PR ?

**Comment by kinarashah** [comment]
@a-blender RKE v1.4.6 will be released around/with Rancher v2.7.5 release, which is currently planned around 6/20 but could change potentially change.

**Comment by a-blender** [comment]
@kinarashah Ok, I don't think we need to wait for this. We'll be updating rke to 1.4.6 for the release anyway and the rke provider should be able to allow 1.25 deployments now. Can you approve?

**Review by kinarashah — APPROVED** [review]

**Comment by tmsdce** [comment]
Hi @a-blender @kinarashah 
Thank you for merging this PR.
Can you publish a new version of the provider to the registry ?

**Comment by margusja** [comment]
Hi. When do you think I can get 1.4.5 provider from https://registry.terraform.io/providers/rancher/rke ?

**Comment by a-blender** [comment]
@margusja @kinarashah We will be waiting to release the TFP rke provider until RKE is updated to 1.4.6 in the upcoming Rancher release. Thank you for your patience.

**Comment by tchernomax** [comment]
> We will be waiting to release the TFP rke provider until RKE is updated to 1.4.6 in the upcoming Rancher release. Thank you for your patience.

@a-blender rke 1.4.6 has just been released : https://github.com/rancher/rke/releases/tag/v1.4.6 :smiley:

**Comment by tsde** [comment]
@tchernomax FYI, I just opened a PR for 1.4.6 : https://github.com/rancher/terraform-provider-rke/pull/405

**Comment by darox** [comment]
May you cut a new release for this PR?

**Pull request merged**
