### PR TITLE
Update RKE dependency to 1.3.7

### PR DESCRIPTION
**Pull request by fe-ax**
According to the changelogs of RKE, there are no changes other than the Rancher hyperkube images. I've tested this, and it works fine.

### CODE REVIEW

**Review by dje4om — COMMENTED** [review]
Hi ! I think CHANGELOG update should not be included in the PR

**Review by VIKMSTR — APPROVED** [review]
Looking good to me. Just bumping the versions.
Tried to build it and run it - everything seems fine and non-breaking.

**Comment by fe-ax** [comment]
Since a new version is out now, I'd like to check this against that version instead. It's a patch version jump so I'm not expecting any breaking changes.

**Comment by VIKMSTR** [comment]
I've tried with 1.3.9 and the build is not working, perhaps some breaking changes in the kube api (0.23.x) :( 
Maybe let`s just remove the Changelog file changes and propose to release this first?

**Comment by fe-ax** [comment]
I've removed the CHANGELOG.md changes. Maybe @rawmind0 can share it's view on how to keep this provider maintained?

**Pull request closed without merging**
