### PR TITLE
Support for RKE 1.0.x

### PR DESCRIPTION
**Pull request by rawmind0**
This PR contains: 
- refactor of the tf provider motivated to be officially supported by Hashicorp. 
- support RKE 1.0.x. 
- hashicorp format documentation
- CHANGELOG.md

The provider is building and working fine. Acceptance tests are not working yet, coming on next PR.

### CODE REVIEW

**Comment by cloudnautique** [comment]
@rawmind0 this has been added to drone. Future pushes to the PR should build.

**Comment by ulm0** [comment]
Hey @rawmind0 I'm using your fork and trying to install cilium as cni, so i need to pass `none` to network plugin. But it doesn't support it

```sh
Error: expected network.0.plugin to be one of [calico canal flannel weave], got none
```

**Comment by ulm0** [comment]
Thanks for fixing the networking part. More on this, now i'm facing an issue when specifying the kubernetes version 

```sh
Error: expected kubernetes_version to be one of [], got v1.16.3-rancher1-1
```

**Comment by rawmind0** [comment]
@ulm0  `kubernetes_version` argument should also be fixed

**Comment by ulm0** [comment]
Yes, the provider has been working good so far!

Thanks a lot.

January 8, 2020 8:40 PM, "Raúl Sánchez" <notifications@github.com (mailto:%22Ra%C3%BAl%20S%C3%A1nchez%22%20<notifications@github.com>)> wrote:
	@ulm0 (https://github.com/ulm0) kubernetes_version argument should also be fixed

**Comment by ulm0** [comment]
@rawmind0 yes, been using the provider for a bit, and it's working good so far.

**Comment by remche** [comment]
FYI, I'm using it for updated [terraform-openstack-rke](https://github.com/remche/terraform-openstack-rke/) with no problem.

**Comment by jbmcfarlin31** [comment]
@rawmind0 is there an ETA for the release of this provider? Seems like the changes have been going good so far, keep up the good work!

**Comment by rawmind0** [comment]
Thanks all for the feedback. 

I'm finishing the docs and i expect to release first version next week.

**Pull request merged**
