### PR TITLE
Update sdk

### PR DESCRIPTION
**Pull request by jakefhyde**
https://github.com/rancher/terraform-provider-rke/issues/353

Updated `terraform-plugin-sdk => v2` so that we can debug the terraform provider.

### CODE REVIEW

**Review by rosskirkpat — CHANGES_REQUESTED** [review]
We should implement some basic unit and integration testing prior to merging to ensure we are not breaking anything. A regression in our terraform provider could potentially wipe out production clusters without a clear-cut recovery path.

**Comment by annablender** [comment]
@jakefhyde Is this PR still needed?

**Comment by jakefhyde** [comment]
@annablender it's a bit out of date but yeah I think it's worth keeping

**Comment by rosskirkpat** [comment]
@annablender @jakefhyde it made my day seeing your names in an email! 😄

**Comment by a-blender** [comment]
@jakefhyde What's the status on this? I'll be doing another TFP rke release soon per majority request

**Comment by jakefhyde** [comment]
@a-blender Given that QA is validating TF releases now I can pick this back up again, probably not for this milestone but for the next?

**Comment by a-blender** [comment]
Starting from the next TFP rke release, we will be branching the provider into separate release lines `master` and `release/v1.3` and be maintaining those release lines separately just like with rancher2. We haven't released TFP rke nearly as often so I want to make sure this goes in if it needs to

**Comment by jakefhyde** [comment]
@a-blender This PR should be ready to review now that we have branched. I'll monitor the build to make sure there aren't any issues.

**Review by a-blender — APPROVED** [review]

**Pull request merged**
