### PR TITLE
Fix false diffs setting

### PR DESCRIPTION
**Pull request by rawmind0**
Fix issues #100, #149 and #151

### CODE REVIEW

**Comment by ulm0** [comment]
Hey @rawmind0 `terraform plan` still prompts for these changes
```sh
...
              ~ extra_env                = [
                  - "RKE_CLOUD_CONFIG_CHECKSUM=acd290168ef8a10d28c99d6abb958f6b",
                  - "RKE_CLOUD_CONFIG_CHECKSUM=acd290168ef8a10d28c99d6abb958f6b",
...
```

**Comment by mitchellmaler** [comment]
kube_config_yaml and rke_cluster_yaml are also always being recreated/recomputed each apply. I would think these shouldn't always be created after the first time or only after cert rotation.
https://github.com/rancher/terraform-provider-rke/issues/151

**Comment by benosman** [comment]
I applied this fix, and still get the issue with kube_config_yaml and rke_cluster_yaml being recreated/recomputed each apply.

In the end, I tracked it down to the `bastion_host` fields needing to be computed. I also had to remove the bastion port default, to make that computed. 

Additionally, in the node schema, I also made `hostname_override` and `internal_address` computed to avoid other diff issues.

#149 
#151

**Comment by jshrack-ssi** [comment]
@benosman  Are you indicating to avoid overrides of any computed fields as a viable interim workaround?

These issues persist into the 1.0.0-rc1. Would be nice to see bothersome issues such as these merged soon into a new release. These are show-stoppers if you have any revisions to an existing plan.

**Comment by benosman** [comment]
@jshrack-ssi 

It was by process of elimination that I found out the bastion host fields were affecting the diff, I wasn't using a bastion, so they were not declared in my resource.

When fields are set to computed false diffs should not be a problem, instead it is when they are not computed and then missing from the resource. If you set an empty value for those fields that might work.

Here are my changes to the bastion host fields:
https://github.com/benosman/terraform-provider-rke/commit/b47bb1914ad024235a127f31ec352258f995b922

When combined with this pull request, it gets me to a stage where it doesn't modify the resource. I haven't tested whether it affects the bastion functionality though.

https://github.com/benosman/terraform-provider-rke/tree/bastion

**Comment by rawmind0** [comment]
Hi all, thanks for the feedback.

Updated PR, addressing all commented issues.

**Pull request merged**
